kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30080
    hostPort: 30080
    protocol: TCP
  extraMounts:
  - hostPath: /Users/lotfinejad/airflow-pyspark-k8s
    containerPath: /Users/lotfinejad/airflow-pyspark-k8s