apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-webserver
  labels:
    app: airflow-webserver
    component: webserver
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  replicas: {{ .Values.airflow.webserver.replicas }}
  selector:
    matchLabels:
      app: airflow-webserver
      component: webserver
  template:
    metadata:
      labels:
        app: airflow-webserver
        component: webserver
    spec:
      initContainers:
      - name: wait-for-postgres
        image: busybox:1.35
        command: 
        - sh
        - -c
        - |
          until nc -z {{ .Values.airflow.database.host }} {{ .Values.airflow.database.port }}; do
            echo "Waiting for PostgreSQL..."
            sleep 2
          done
          echo "PostgreSQL is ready!"
      - name: wait-for-db-init
        image: "{{ .Values.airflow.image.repository }}:{{ .Values.airflow.image.tag }}"
        command:
        - sh
        - -c
        - |
          until airflow db check; do
            echo "Waiting for database initialization..."
            sleep 5
          done
          echo "Database is initialized!"
        envFrom:
        - configMapRef:
            name: airflow-config
      containers:
      - name: airflow-webserver
        image: "{{ .Values.airflow.image.repository }}:{{ .Values.airflow.image.tag }}"
        imagePullPolicy: {{ .Values.airflow.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.airflow.webserver.port }}
          name: webserver
        command: ["airflow", "webserver"]
        envFrom:
        - configMapRef:
            name: airflow-config
        volumeMounts:
        - name: dags
          mountPath: /opt/airflow/dags
        - name: scripts
          mountPath: /opt/airflow/scripts
        - name: logs
          mountPath: /opt/airflow/logs
        - name: plugins
          mountPath: /opt/airflow/plugins
        livenessProbe:
          httpGet:
            path: /health
            port: {{ .Values.airflow.webserver.port }}
          initialDelaySeconds: 120
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /health
            port: {{ .Values.airflow.webserver.port }}
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 3
        resources:
          {{- toYaml .Values.resources.webserver | nindent 10 }}
      volumes:
      - name: dags
        hostPath:
          path: {{ .Values.volumes.hostPaths.dags }}
          type: DirectoryOrCreate
      - name: scripts
        hostPath:
          path: {{ .Values.volumes.hostPaths.scripts }}
          type: DirectoryOrCreate
      - name: logs
        hostPath:
          path: {{ .Values.volumes.hostPaths.logs }}
          type: DirectoryOrCreate
      - name: plugins
        hostPath:
          path: {{ .Values.volumes.hostPaths.plugins }}
          type: DirectoryOrCreate