# templates/airflow-scheduler-deployment.yaml
# --------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-scheduler
  labels:
    app: airflow-scheduler
spec:
  replicas: {{ .Values.airflow.scheduler.replicas }}
  selector:
    matchLabels:
      app: airflow-scheduler
  template:
    metadata:
      labels:
        app: airflow-scheduler
    spec:
      serviceAccountName: airflow-scheduler
      initContainers:
        - name: wait-for-postgres
          image: busybox:1.35
          command:
            - sh
            - -c
            - |
              until nc -z {{ .Values.airflow.database.host }} {{ .Values.airflow.database.port }}; do
                echo "Waiting for PostgreSQL..."
                sleep 2
              done
              echo "PostgreSQL is ready!"
        - name: init-db
          image: "{{ .Values.airflow.image.repository }}:{{ .Values.airflow.image.tag }}"
          imagePullPolicy: {{ .Values.airflow.image.pullPolicy }}
          command:
            - sh
            - -c
            - airflow db init
          envFrom:
            - configMapRef:
                name: airflow-config

      containers:
        - name: airflow-scheduler
          image: "{{ .Values.airflow.image.repository }}:{{ .Values.airflow.image.tag }}"
          imagePullPolicy: {{ .Values.airflow.image.pullPolicy }}
          command: ["airflow", "scheduler"]
          envFrom:
            - configMapRef:
                name: airflow-config
          volumeMounts:
            - name: dags
              mountPath: /opt/airflow/dags
            - name: scripts
              mountPath: /opt/airflow/scripts
            - name: logs
              mountPath: /opt/airflow/logs
            - name: plugins
              mountPath: /opt/airflow/plugins
            - name: pod-template
              mountPath: /opt/airflow/pod-template
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - airflow jobs check --job-type SchedulerJob --hostname $(hostname)
            initialDelaySeconds: {{ .Values.airflow.scheduler.livenessProbe.initialDelaySeconds | default 60 }}
            periodSeconds: {{ .Values.airflow.scheduler.livenessProbe.periodSeconds | default 30 }}
            timeoutSeconds: {{ .Values.airflow.scheduler.livenessProbe.timeoutSeconds | default 10 }}
            failureThreshold: {{ .Values.airflow.scheduler.livenessProbe.failureThreshold | default 5 }}

          resources:
            {{- toYaml .Values.resources.scheduler | nindent 12 }}

      volumes:
        - name: dags
          hostPath:
            path: {{ .Values.volumes.hostPaths.dags }}
            type: DirectoryOrCreate
        - name: scripts
          hostPath:
            path: {{ .Values.volumes.hostPaths.scripts }}
            type: DirectoryOrCreate
        - name: logs
          hostPath:
            path: {{ .Values.volumes.hostPaths.logs }}
            type: DirectoryOrCreate
        - name: plugins
          hostPath:
            path: {{ .Values.volumes.hostPaths.plugins }}
            type: DirectoryOrCreate
        - name: pod-template
          configMap:
            name: worker-pod-template
