apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-config
  labels:
    app: airflow
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
data:
  AIRFLOW__CORE__EXECUTOR: {{ .Values.airflow.executor }}
  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://{{ .Values.airflow.database.username }}:{{ .Values.airflow.database.password }}@{{ .Values.airflow.database.host }}:{{ .Values.airflow.database.port }}/{{ .Values.airflow.database.database }}
  AIRFLOW__CORE__LOAD_EXAMPLES: "False"
  AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "True"
  AIRFLOW__CORE__FERNET_KEY: "81HqDtbqAywKSOumSha3BhWNOdQ26slT6K0YaZeZyPs="
  AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "True"
  AIRFLOW__API__AUTH_BACKENDS: "airflow.api.auth.backend.basic_auth"
  # JAVA_HOME: "/usr/lib/jvm/java-17-openjdk-amd64"
  JAVA_HOME: "/usr/lib/jvm/java-17-openjdk-arm64"
  SPARK_HOME: "/home/airflow/.local/lib/python3.8/site-packages/pyspark"